name: main_workflow
on:
  push:
    branches:
    - nodejs_linter_job 
jobs:
  linter-execution:
    runs-on: ubuntu-latest
    steps: 
    - name: Checkout
      uses: actions/checkout@v2.4.0
    - name: Super-Linter
      env:
        DEFAULT_BRANCH: nodejs_linter_job
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        LINTER_RULES_PATH: /
        JAVASCRIPT_ES_CONFIG_FILE: .eslintrc.json
        VALIDATE_JAVASCRIPT_ES: true
      uses: github/super-linter@v4.8.4
  build:
    needs: linter-execution
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ '10', '12' ]
    name: Node ${{ matrix.node }} sample
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - run: npm install
      - run: npm test
  test-execution:
    needs: build
    runs-on: ubuntu-latest
    steps: 
    - name: Checkout
      uses: actions/checkout@v2.4.0
    - run: npm install jest 
    - run: npm run test 
  environment_test_execution:
    needs: test-execution
    runs-on: ubuntu-latest
    steps: 
    - name: Checkout
      uses: actions/checkout@v2.4.0
    - name: Hello world javascript action
      uses: adeloyedeji/github-actions-hello@v1.0
      env:
        DESTINATION_PERSON: 2DAW
      with: 
        who-to-greet: ${ DESTINATION_PERSON } 


