name: main_workflow
on:
  push:
    branches:
    - nodejs_linter_job 
jobs:
  linter-execution:
    runs-on: ubuntu-latest
    steps: 
    - name: Checkout
      uses: actions/checkout@v2.4.0
    - name: Super-Linter
      env:
        DEFAULT_BRANCH: nodejs_linter_job
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        LINTER_RULES_PATH: /
        JAVASCRIPT_ES_CONFIG_FILE: .eslintrc.json
        VALIDATE_JAVASCRIPT_ES: true
      uses: github/super-linter@v4.8.4
  test-execution:
    runs-on: ubuntu-latest
    steps: 
    - name: Checkout
      uses: actions/checkout@v2.4.0
    - run: npm install jest 
    - run: npm run test 